language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "stable"

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

before_script: npm install -g standard
